### ISSUE TITLE
Non minified version

### ISSUE THREAD

**Issue by manpreeeeeet** [gerwld/igplus-extension#2]
Hi can you please update this repo to included non minified version of the extension code? Currently all the JS/CSS files are minified to only one line, which makes it harder to read.

**Comment by gerwld** [comment]
Hi, [manpreeeeeet](https://github.com/manpreeeeeet)! The project has been released as Open Source starting from commit https://github.com/gerwld/igplus-extension/commit/db4adcf0d8885d3ee6f2959fe7399da4590e3e7d

**Comment by gerwld** [comment]
This issue is marked as closed. Create a new one if you suggest it's not true
