### ISSUE TITLE
Instagram only shows white page when disable recommendations is on

### ISSUE THREAD

**Issue by piratenpanda** [gerwld/igplus-extension#6]
Since yesterday I only get a white page when starting with variant=following. After disabling the setting, putting my profile into the url bar and then going to "home" it works. Also the variant=following url is the same and still works. I don't know if meta changed something on their end.

This is on Arch Linux, latest packages, Firefox 127.0.2

**Comment by piratenpanda** [comment]
ok it does not depend on disable recommendations as i randomly got a white page now. Maybe instagram is just broken...

**Comment by gerwld** [comment]
> Since yesterday I only get a white page when starting with variant=following. After disabling the setting, putting my profile into the url bar and then going to "home" it works. Also the variant=following url is the same and still works. I don't know if meta changed something on their end.
> 
> This is on Arch Linux, latest packages, Firefox 127.0.2

Hi [piratenpanda](https://github.com/piratenpanda), at first sorry for the late reply. I guess that other extensions can also cause that error, for example Ublock. Instagram website is based mostly on React.js, so everything that can cause error in loading some assets may cause a blank page. Are there any related errors on the DevTools network / console page?

**Comment by gerwld** [comment]
I closed this issue. If the problem persists, you may open the new issue
